/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"Global Nav","global-nav",0),
(3,"Sections","sections",0),
(4,"global","global",0),
(5,"section","section",0),
(6,"regular","regular",0),
(7,"Footer nav","footer-nav",0),
(8,"Footer social","footer-social",0),
(9,"eSpots","espots",0),
(10,"not_global","not_global",0),
(11,"row","row",0),
(12,"Company Timeline","company-timeline",0),
(13,"IBM Commerce","ibm-commerce",0),
(14,"General","general",0),
(15,"Digital Marketing","digital-marketing",0),
(16,"eCommerce","ecommerce",0),
(17,"BlueSky Cares","bluesky-cares",0),
(18,"News and Events","news-and-events",0),
(19,"Analytics","analytics",0),
(20,"Cloud Solutions","cloud-solutions",0),
(21,"Landing Pages","landing-pages",0),
(22,"BlueSky Cares","bluesky-cares",0),
(23,"brooke\'s place","brookes-place",0),
(24,"Digital Marketing","digital-marketing",0),
(25,"IBM Journey Designer","ibm-journey-designer",0),
(26,"IBM Marketing Cloud","ibm-marketing-cloud",0),
(27,"digital marketing platforms","digital-marketing-platforms",0),
(28,"IBM","ibm",0),
(29,"IBM WebSphere Commerce","ibm-websphere-commerce",0),
(30,"WebSphere Commerce V8","websphere-commerce-v8",0),
(31,"Commerce on Cloud","commerce-on-cloud",0),
(32,"Events","events",0),
(33,"Shop.org","shop-org",0),
(34,"case study","case-study",0),
(35,"client success","client-success",0),
(36,"eCommerce","ecommerce",0),
(37,"hhgregg","hhgregg",0),
(38,"IBM Journey Analytics","ibm-journey-analytics",0),
(39,"IBM UBX","ibm-ubx",0),
(40,"IBM Universal Behavior Exchange","ibm-universal-behavior-exchange",0),
(41,"MediaMath","mediamath",0),
(42,"Silverpop","silverpop",0),
(43,"b2b ecommerce","b2b-ecommerce",0),
(44,"ecommerce strategy","ecommerce-strategy",0),
(45,"BlueSky Insights","bluesky-insights",0),
(46,"Case Studies","case-studies",0),
(47,"Customer Experience Management","customer-experience-management",0),
(48,"IBM Tealeaf","ibm-tealeaf",0),
(49,"Atlassian","atlassian",0),
(50,"BluePrint","blueprint",0),
(51,"Project Management","project-management",0),
(52,"IBM Commerce Configurator","ibm-commerce-configurator",0),
(53,"Sterling Configurator","sterling-configurator",0),
(54,"IBM Commerce Composer","ibm-commerce-composer",0),
(55,"IBM Commerce Insights","ibm-commerce-insights",0),
(56,"dynatrace","dynatrace",0),
(57,"IBM Commerce","ibm-commerce",0),
(58,"NRF 2016","nrf-2016",0),
(59,"b2c ecommerce","b2c-ecommerce",0),
(60,"eBooks","ebooks",0),
(61,"Shopping Cart Abandonment","shopping-cart-abandonment",0),
(62,"BlueSky Insights","bluesky-insights",0),
(63,"Case Studies","case-studies",0),
(64,"Trivantage","trivantage",0),
(65,"Headquarters","headquarters",0),
(66,"Hipstoric","hipstoric",0),
(67,"Indiana","indiana",0),
(68,"Noblesville","noblesville",0),
(69,"User Experience Design","user-experience-design",0),
(70,"IBM Watson","ibm-watson",0),
(71,"BigCommerce","bigcommerce",0),
(72,"Press Release","press-release",0),
(73,"social-ads","social-ads",0),
(74,"Customer Survey","customer-survey",0),
(75,"Featured","featured",0);
